### ISSUE TITLE
Program.port overrides config.port every time

### ISSUE THREAD

**Issue by arieljake** [nathangoulding/grpcli#9]
https://github.com/nathangoulding/grpcli/blob/ccc98f53cb66366f60e51d589c97111e634054ea/bin/grpcli.js#L94

I am unable to specify a port in the config file as the default '8080' is always present in the program object.

**Comment by nathangoulding** [comment]
@arieljake good catch! Would you mind working up a PR?

**Comment by nathangoulding** [comment]
Fixed in #10
